// Attribution patterns that must never reach a commit, PR, ticket comment, or doc.
//
// These target ATTRIBUTION specifically, not any mention of a tool name. That
// distinction matters: "add claude commands" is a legitimate commit subject in
// this very repo, while "Co-Authored-By: Claude" never is.

export const ATTRIBUTION_PATTERNS = [
  { re: /co-?authored-by:\s*[^\n]*\b(claude|anthropic|copilot|cursor|codex|gemini|chatgpt|openai|devin|bot)\b/i, why: 'AI co-author trailer' },
  { re: /co-?authored-by:\s*[^\n]*@(anthropic|openai)\.com/i, why: 'AI vendor co-author email' },
  { re: /\bclaude-session:\s*http/i, why: 'Claude session trailer' },
  { re: /generated\s+with\s+\[?\s*(claude|chatgpt|copilot|cursor|gemini|codex)/i, why: '"Generated with <tool>" line' },
  { re: /🤖\s*generated/i, why: 'robot-emoji generated line' },
  { re: /\b(ai|llm)[-\s]?(generated|authored|assisted|written|created)\b/i, why: 'AI authorship claim' },
  { re: /\bgenerated\s+by\s+(an?\s+)?(ai|llm|claude|chatgpt|copilot|cursor|gemini)\b/i, why: '"Generated by AI" claim' },
  { re: /\b(written|created|authored|produced)\s+(by|with)\s+(claude|chatgpt|copilot|cursor|gemini|an?\s+ai)\b/i, why: 'AI authorship claim' },
  { re: /\bwith\s+(the\s+)?(help|assistance)\s+of\s+(claude|chatgpt|copilot|an?\s+ai)\b/i, why: 'AI assistance credit' },
  { re: /\bvia\s+claude\s+code\b/i, why: 'Claude Code credit' },
  { re: /\b(assisted|authored)-by:\s*[^\n]*\b(claude|ai|gpt)\b/i, why: 'AI assistance trailer' },
  { re: /noreply@anthropic\.com/i, why: 'Anthropic noreply address' },
]

// Emails that must never appear as a git author or committer. Sourced from a
// standing rule, not a guess — see docs/rules.md.
export const BANNED_AUTHOR_DOMAINS = [/@technotribes\.org$/i]

export function findAttribution(text) {
  if (!text) return []
  const hits = []
  for (const { re, why } of ATTRIBUTION_PATTERNS) {
    const m = text.match(re)
    if (m) hits.push({ why, match: m[0].trim().slice(0, 120) })
  }
  return hits
}

export function assertClean(text, label) {
  const hits = findAttribution(text)
  if (hits.length) {
    const lines = hits.map((h) => `  - ${h.why}: "${h.match}"`).join('\n')
    throw new Error(`${label} contains AI attribution and was not sent:\n${lines}\n\nRewrite it without any tool or AI credit.`)
  }
  return text
}

// Best-effort removal, for the `work scrub` escape hatch. Whole matched lines go,
// because attribution nearly always lives on its own line (trailers, footers).
export function scrub(text) {
  const kept = text
    .split('\n')
    .filter((line) => !ATTRIBUTION_PATTERNS.some(({ re }) => re.test(line)))
  return kept.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
}
